### ISSUE TITLE
Question: raspberry pi and compatible usb jtag

### ISSUE THREAD

**Issue by rdpeake** [Xilinx/XilinxVirtualCable#11]
Does something exist that uses this protocol, to enable a raspberry pi connected to a compatible usb jtag device such that vivado running on a pc can remotely access the fpga connected to the pi in place of vivado not being available to run on a raspberry pi (given it is arm).

Does anything else exists that can do this that already exists (not sure if usbip is reliable enough)?

Can this protocol be used to connect a pi as a remote link to an fpga via usb jtag if someone were to create the server file that translates it to ftdi jtag commands?

**Comment by adrianh-xlnx** [comment]
@rdpeake since XVC is just a protocol it should be possible to take the protocol described in the [README.md](https://github.com/Xilinx/XilinxVirtualCable/blob/master/README.md) and wrap it around code that drives FTDI.  The code from the [versal source](https://github.com/Xilinx/XilinxVirtualCable/tree/master/versal/src) could be a reasonable starting point to begin with for the base XVC server communication then replace the [xvc_mem.c](https://github.com/Xilinx/XilinxVirtualCable/blob/master/versal/src/xvc_mem.c) with source code that drives the FTDI.

**Comment by derekmulcahy** [comment]
Is this relevant?

https://github.com/derekmulcahy/xvcpi
