### ISSUE TITLE
Missing driver for Zynq-7000?

### ISSUE THREAD

**Issue by Livius90** [Xilinx/XilinxVirtualCable#12]
Hi!

I try to following this [wiki article](https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/644579329/Xilinx+Virtual+Cable#Software) about the building and using Xilinx Virtual Cable for **Zynq-7000** but it seems to me there are lots of out-dated details in it.

Now, in the current repo, there are no any driver source in _zynq7000/XAPP1251/src/_. Where can i get the **kernel module xvc-driver.ko sources** for **Zynq-7000** in this repo?

**Comment by prashant-mehta** [comment]
Hi @Livius90 ,

The xvcserver in zynq7000/XAPP1251/src/ use /dev/uio0 to mmap the debug bridge or AXI-JTAG IP. This /dev/uio0 file is created using generic UIO driver framework which is part of the kernel. So the Zynq 7000 source directory does not include driver sources. You can refer to [XAPP1251](https://docs.xilinx.com/v/u/en-US/xapp1251-xvc-zynq-petalinux) on how to update the device tree node of an IP to use the UIO driver.

Alternatively, instead of UIO driver you can also use the XVC driver source code for Zynq Ultrascale+ in [zynqMP/src/driver](https://github.com/Xilinx/XilinxVirtualCable/tree/master/zynqMP/src/driver) and follow the steps on this [wiki page](https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/644579329/Xilinx+Virtual+Cable) to use XVC on a Zynq 7000 platform.

**Comment by Livius90** [comment]
> Alternatively, instead of UIO driver you can also use the XVC driver source code for Zynq Ultrascale+ in [zynqMP/src/driver](https://github.com/Xilinx/XilinxVirtualCable/tree/master/zynqMP/src/driver) and follow the steps on this [wiki page](https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/644579329/Xilinx+Virtual+Cable) to use XVC on a Zynq 7000 platform.

Does it mean, debug bridge IP block and [XilinxVirtualCable](https://github.com/Xilinx/XilinxVirtualCable)/[zynqMP](https://github.com/Xilinx/XilinxVirtualCable/tree/master/zynqMP/src/) are also supported to use in Zynq-7000 SoCs, so XVC 1.1 is copmatible with Zynq-7000?

**Comment by prashant-mehta** [comment]
Debug bridge IP in AXI to BSCAN mode and XVC source code in [zynqMP/src](https://github.com/Xilinx/XilinxVirtualCable/tree/master/zynqMP/src) can work on Zynq 7000 embedded platform as well. Both - Zynq 7000 and Zynq MP XVC server source code support XVC 1.0 protocol.

**Comment by Noah-naihe** [comment]
Hi, I'm having a similar problem here.
The mode used by vivado is From axi tojtag. I built the xvc post on xilinx Wikipedia. I saw the introduction on github that the driver used can be the UIO driver. In this, I added the debug bridge node and removed the node, but no UIO node appeared.
